### PR TITLE
[data_processing][rne]Download RNE stock files using ftp instead of https

### PR DESCRIPTION
**Pull request by HAEKADI**
INPI changed where RNE stock files are stored. They are no longer accessible from a web page but can only be downloaded via ftp.

### CODE REVIEW

**Review by Pierlou — APPROVED** [review]
Looks good to me, but I'm curious: why did you switch to bash instead of python for this?

**Review by XavierJp — APPROVED** [review]
Nice. Is lftp always installed on debian distros ?

**Comment by HAEKADI** [comment]
@Pierlou it is easier in my opinion and offers a more direct access since `lftp` is already installed with with the Docker file. Doable with `ftplib` on Python as well. Just a personal choice to mix it up ;)

**Comment by HAEKADI** [comment]
@XavierJp No it's not, but it is installed in with docker in our data engineering stack for potential use https://github.com/etalab/data-engineering-stack/blob/d685a149fcae4261ddf659c3df3a80daa5b97111/Dockerfile#L21.

**Pull request merged**
